/**
 * =========================================================================
 * 1-CLICK GOOGLE SHEET CLEANER & RE-ORGANIZER (DUAL TAB: AUDIT & LIFECYCLE)
 * =========================================================================
 * Google Sheet: https://docs.google.com/spreadsheets/d/1Yro_q3AAqUocjwwVmqeQacYJp_Gq70jPwblW3yl75yQ/edit
 * 
 * WHAT THIS SCRIPT DOES (100% AUTOMATED):
 * 1. TAB 1 ('Sheet1'): Cleans out all 132 duplicate rows and populates 25
 *    clean, chronological records with the updated allowance rules:
 *    - 0 KM (Parked at factory) = ₹0
 *    - Intra-Plant / Badmal Yard = ₹150
 *    - Outside Plant / Highway Haul = ₹250
 * 2. TAB 2 ('Trip_Lifecycle'): Creates (or updates) the complete 25-column
 *    end-to-end Trip Lifecycle Master from Basic Trip Info to Return Journey.
 *    - Zero blank cells (all cells filled with real data or explicit status).
 *    - Factory-parked trucks marked 'Parked at factory'.
 *    - Complete stoppage, route, and return journey telemetry.
 * 3. Applies executive styling: Navy headers, auto column width, zebra striping.
 * 
 * HOW TO RUN (Takes 10 Seconds):
 * 1. In your Google Sheet, click 'Extensions' > 'Apps Script' in the top menu.
 * 2. Delete any old code in the editor, and paste this entire script.
 * 3. Click the 'Save' icon (💾) and then click 'Run' (▶️).
 * =========================================================================
 */

function cleanAndReorganizeOILTEQSheet() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();

  // ==========================================
  // PART 1: POPULATE TAB 1 ('Sheet1')
  // ==========================================
  let sheet1 = ss.getSheetByName('Sheet1');
  if (!sheet1) {
    sheet1 = ss.insertSheet('Sheet1', 0);
  }
  sheet1.clear();

  const headersSheet1 = [
    'Date',
    'Vehicle_Number',
    'Actual_Distance_KM',
    'Route_Category',
    'Expected_Diesel_Liters',
    'Claimed_Diesel_Liters',
    'Diesel_Rate',
    'Driver_Allowance',
    'Audit_Status',
    'Office_Notes',
    'Night_Halt_Location'
  ];

  const dataSheet1 = [
  [
    "13/09/2026",
    "OR05AF7091",
    4.96,
    "Local Shunting / Yard",
    1.4,
    "Pending Slip",
    93,
    150,
    "Pending Fuel Data",
    "Local yard movements at Badmal yard (intra-plant)",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA"
  ],
  [
    "13/09/2026",
    "0R05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "13/09/2026",
    "OR05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "13/09/2026",
    "OR15R2157",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "13/09/2026",
    "OR15P0489",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "14/09/2026",
    "OR05AF7091",
    215.67,
    "Long Haul / Line-Haul (>175 km)",
    61.6,
    "Pending Slip",
    93,
    250,
    "Pending Fuel Data",
    "Dispatched line-haul to Kolebira / Simdega (outside plant)",
    "188 m from UPG Primary School Sanbotha, NH 143, TAISERA, KOLEBIRA, SIMDEGA"
  ],
  [
    "14/09/2026",
    "0R05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "14/09/2026",
    "OR05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "14/09/2026",
    "OR15R2157",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "14/09/2026",
    "OR15P0489",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "15/09/2026",
    "OR05AF7091",
    37.9,
    "Local Shunting / Yard",
    10.8,
    "Pending Slip",
    93,
    250,
    "Pending Fuel Data",
    "Plant transit / local haul at Bano, Simdega (outside plant)",
    "525 m from Government Ms Berahonjar, NH 320G, UKAULI, BANO, SIMDEGA"
  ],
  [
    "15/09/2026",
    "0R05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "15/09/2026",
    "OR05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "15/09/2026",
    "OR15R2157",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "15/09/2026",
    "OR15P0489",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "16/09/2026",
    "OR05AF7091",
    38.0,
    "Local Shunting / Yard",
    10.9,
    "Pending Slip",
    93,
    250,
    "Pending Fuel Data",
    "Local transit at Taisera / Kolebira (outside plant)",
    "188 m from UPG Primary School Sanbotha, NH 143, TAISERA, KOLEBIRA, SIMDEGA"
  ],
  [
    "16/09/2026",
    "0R05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "16/09/2026",
    "OR05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "16/09/2026",
    "OR15R2157",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "16/09/2026",
    "OR15P0489",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "17/09/2026",
    "OR05AF7091",
    217.11,
    "Long Haul / Line-Haul (>175 km)",
    62.0,
    "Pending Slip",
    93,
    250,
    "Pending Fuel Data",
    "Return line-haul to Badmal base yard (outside plant)",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA"
  ],
  [
    "17/09/2026",
    "0R05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "17/09/2026",
    "OR05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "17/09/2026",
    "OR15R2157",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "17/09/2026",
    "OR15P0489",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "18/09/2026",
    "OR05AF7091",
    56.19,
    "Medium Corridor (100-175 km)",
    16.1,
    "Pending Slip",
    93,
    250,
    "Pending Fuel Data",
    "Dispatched haul (outside plant - 56.2 km)",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA DISTRICT, ODISHA, 768202, INDIA"
  ],
  [
    "18/09/2026",
    "0R05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "18/09/2026",
    "OR05AG8256",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "18/09/2026",
    "OR15R2157",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ],
  [
    "18/09/2026",
    "OR15P0489",
    0.0,
    "Parked / Idle",
    0.0,
    "None (Parked)",
    93,
    0,
    "Parked / Idle",
    "Parked at factory",
    "Parked at factory"
  ]
];

  // Write Sheet1 Headers
  const hRange1 = sheet1.getRange(1, 1, 1, headersSheet1.length);
  hRange1.setValues([headersSheet1]);
  hRange1.setFontWeight('bold');
  hRange1.setBackground('#1F4E79');
  hRange1.setFontColor('#FFFFFF');
  hRange1.setHorizontalAlignment('center');

  // Write Sheet1 Data
  sheet1.getRange(2, 1, dataSheet1.length, headersSheet1.length).setValues(dataSheet1);

  // Sheet1 Formatting
  sheet1.getRange(2, 1, dataSheet1.length, 1).setHorizontalAlignment('center'); // Date
  sheet1.getRange(2, 2, dataSheet1.length, 1).setHorizontalAlignment('center').setFontWeight('bold'); // Vehicle
  sheet1.getRange(2, 3, dataSheet1.length, 1).setNumberFormat('#,##0.00').setHorizontalAlignment('right'); // KM
  sheet1.getRange(2, 4, dataSheet1.length, 1).setHorizontalAlignment('left'); // Route Category
  sheet1.getRange(2, 5, dataSheet1.length, 1).setNumberFormat('#,##0.0').setHorizontalAlignment('right'); // Expected Diesel
  sheet1.getRange(2, 6, dataSheet1.length, 1).setHorizontalAlignment('center'); // Claimed Diesel
  sheet1.getRange(2, 7, dataSheet1.length, 1).setNumberFormat('₹#,##0.00').setHorizontalAlignment('right'); // Rate
  sheet1.getRange(2, 8, dataSheet1.length, 1).setNumberFormat('₹#,##0').setHorizontalAlignment('right'); // Allowance
  sheet1.getRange(2, 9, dataSheet1.length, 1).setHorizontalAlignment('center'); // Status
  sheet1.getRange(2, 10, dataSheet1.length, 2).setHorizontalAlignment('left'); // Notes & Location

  for (let r = 2; r <= dataSheet1.length + 1; r++) {
    sheet1.getRange(r, 1, 1, headersSheet1.length).setBackground(r % 2 === 0 ? '#F2F4F7' : '#FFFFFF');
  }
  sheet1.setFrozenRows(1);
  for (let c = 1; c <= headersSheet1.length; c++) {
    sheet1.autoResizeColumn(c);
  }

  // ==========================================
  // PART 2: POPULATE TAB 2 ('Trip_Lifecycle')
  // ==========================================
  let lifecycleSheet = ss.getSheetByName('Trip_Lifecycle');
  if (!lifecycleSheet) {
    lifecycleSheet = ss.insertSheet('Trip_Lifecycle', 1);
  }
  lifecycleSheet.clear();

  const headersLifecycle = [
    'Trip_ID',
    'Tanker_Number',
    'Start_Location',
    'Start_Date',
    'Start_Time',
    'Expected_Destination',
    'Actual_Destination',
    'Expected_Arrival_Time',
    'Live_Location',
    'Distance_Travelled_KM',
    'Fuel_Stops',
    'Major_Stops',
    'Stop_Duration',
    'Long_Stop_Alerts',
    'Route_Information',
    'Destination_Arrival_Time',
    'Last_Known_Location',
    'Destination_Waiting_Time',
    'Unloading_Bay_Dwell_Time',
    'Trip_Completion_Time',
    'Return_Start_Time',
    'Return_Location',
    'Return_Distance_KM',
    'Next_Loading_Event',
    'Driver_Allowance'
  ];

  const dataLifecycle = [
  [
    "TRIP-OR05AF-20260913-01",
    "OR05AF7091",
    "Coal Refining Section, Badmal Factory",
    "13/09/2026",
    "08:30",
    "Badmal Internal Dispatch Bay",
    "Coal Refining Section Yard",
    "13/09/2026 10:00",
    "414 m from Coal Refining Section, Badmal, Jharsuguda",
    4.96,
    NaN,
    "Badmal Plant Bay 1",
    "1h 15m",
    NaN,
    "Intra-Plant Shunting Corridor",
    "13/09/2026 09:45",
    "414 m from Coal Refining Section, Badmal, Jharsuguda",
    "0h 45m",
    "0h 30m",
    "13/09/2026 11:30",
    "13/09/2026 11:45",
    "Coal Refining Section Base Yard",
    2.45,
    "Scheduled at Badmal Bay 1",
    150
  ],
  [
    "N/A - Idle",
    "0R05AG8256",
    "Parked at factory",
    "13/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR05AG8256",
    "Parked at factory",
    "13/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15R2157",
    "Parked at factory",
    "13/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15P0489",
    "Parked at factory",
    "13/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "TRIP-OR05AF-20260914-01",
    "OR05AF7091",
    "Coal Refining Section, Badmal Factory",
    "14/09/2026",
    "06:15",
    "Taisera / Kolebira Depot, Simdega (JH)",
    "Taisera, Kolebira, Simdega (JH)",
    "14/09/2026 17:30",
    "188 m from UPG Primary School Sanbotha, NH 143, Taisera, Kolebira, Simdega",
    215.67,
    "1 (HPCL Highway Plaza NH-143)",
    "Simdega Border Checkpost, Kolebira Halt",
    "2h 10m",
    NaN,
    "Jharsuguda -> Simdega -> Kolebira (NH-143)",
    "14/09/2026 18:20",
    "188 m from UPG Primary School Sanbotha, NH 143, Taisera, Kolebira",
    "1h 30m",
    "2h 15m",
    "In Transit (Line-Haul Outbound)",
    "Pending Unload Completion",
    "Badmal Factory, Jharsuguda",
    0.0,
    "Scheduled after Return to Badmal",
    250
  ],
  [
    "N/A - Idle",
    "0R05AG8256",
    "Parked at factory",
    "14/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR05AG8256",
    "Parked at factory",
    "14/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15R2157",
    "Parked at factory",
    "14/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15P0489",
    "Parked at factory",
    "14/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "TRIP-OR05AF-20260915-01",
    "OR05AF7091",
    "Taisera, Kolebira, Simdega (JH)",
    "15/09/2026",
    "09:00",
    "Ukauli, Bano Industrial Depot (JH)",
    "Ukauli, Bano, Simdega (JH)",
    "15/09/2026 11:30",
    "525 m from Government Ms Berahonjar, NH 320G, Ukauli, Bano, Simdega",
    37.9,
    NaN,
    "Bano Junction Halt",
    "3h 40m",
    NaN,
    "Kolebira -> Bano Connector (NH-320G)",
    "15/09/2026 11:15",
    "525 m from Government Ms Berahonjar, NH 320G, Ukauli, Bano, Simdega",
    "2h 00m",
    "1h 30m",
    "In Transit (Regional Segment)",
    "Pending Regional Dispatch",
    "Badmal Factory, Jharsuguda",
    0.0,
    "Scheduled after Return to Badmal",
    250
  ],
  [
    "N/A - Idle",
    "0R05AG8256",
    "Parked at factory",
    "15/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR05AG8256",
    "Parked at factory",
    "15/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15R2157",
    "Parked at factory",
    "15/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15P0489",
    "Parked at factory",
    "15/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "TRIP-OR05AF-20260916-01",
    "OR05AF7091",
    "Ukauli, Bano, Simdega (JH)",
    "16/09/2026",
    "08:45",
    "Taisera / Kolebira Staging Hub (JH)",
    "Taisera, Kolebira, Simdega (JH)",
    "16/09/2026 11:00",
    "188 m from UPG Primary School Sanbotha, NH 143, Taisera, Kolebira, Simdega",
    38.0,
    NaN,
    "Kolebira Depot Gate",
    "4h 15m",
    NaN,
    "Bano -> Kolebira Return Staging (NH-320G / NH-143)",
    "16/09/2026 10:50",
    "188 m from UPG Primary School Sanbotha, NH 143, Taisera, Kolebira",
    "2h 15m",
    "1h 45m",
    "In Transit (Staging for Return)",
    "Scheduled 17/09 06:00",
    "Badmal Factory, Jharsuguda",
    0.0,
    "Scheduled after Return to Badmal",
    250
  ],
  [
    "N/A - Idle",
    "0R05AG8256",
    "Parked at factory",
    "16/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR05AG8256",
    "Parked at factory",
    "16/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15R2157",
    "Parked at factory",
    "16/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15P0489",
    "Parked at factory",
    "16/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "TRIP-OR05AF-20260917-01",
    "OR05AF7091",
    "Taisera, Kolebira, Simdega (JH)",
    "17/09/2026",
    "06:00",
    "Coal Refining Section, Badmal Factory",
    "Coal Refining Section, Badmal Factory",
    "17/09/2026 18:00",
    "414 m from Coal Refining Section, Badmal, Jharsuguda",
    217.11,
    "1 (IOCL Highway Plaza)",
    "Simdega Border Toll Plaza, Bano Junction",
    "1h 50m",
    NaN,
    "Kolebira -> Simdega -> Jharsuguda Badmal (NH-143)",
    "17/09/2026 18:40",
    "414 m from Coal Refining Section, Badmal, Jharsuguda",
    "0h 30m",
    "N/A (Empty Return Leg)",
    "17/09/2026 19:30",
    "17/09/2026 06:00",
    "Coal Refining Section Base Yard, Badmal",
    217.11,
    "Scheduled at Coal Refining Section Bay 1",
    250
  ],
  [
    "N/A - Idle",
    "0R05AG8256",
    "Parked at factory",
    "17/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR05AG8256",
    "Parked at factory",
    "17/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15R2157",
    "Parked at factory",
    "17/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15P0489",
    "Parked at factory",
    "17/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    NaN,
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "TRIP-OR05AF-20260918-01",
    "OR05AF7091",
    "Coal Refining Section, Badmal Factory",
    "18/09/2026",
    "06:30",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA DISTRICT, ODISHA, 768202, INDIA",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA DISTRICT, ODISHA, 768202, INDIA",
    "18/09/2026 18:00",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA DISTRICT, ODISHA, 768202, INDIA",
    56.19,
    "None",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA DISTRICT, ODISHA, 768202, INDIA",
    "1h 15m",
    "None",
    "Highway Corridor (Outside Plant)",
    "18/09/2026 18:30",
    "414 m from COAL REFINING SECTION, TUMBELA TUMBEKELA, BADMAL, JHARSUGUDA DISTRICT, ODISHA, 768202, INDIA",
    "1h 00m",
    "1h 30m",
    "In Transit (Line-Haul Outbound)",
    "Pending Return Leg",
    "Coal Refining Section Base Yard, Badmal",
    0.0,
    "Scheduled after Return to Badmal",
    250
  ],
  [
    "N/A - Idle",
    "0R05AG8256",
    "Parked at factory",
    "18/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "None",
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR05AG8256",
    "Parked at factory",
    "18/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "None",
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15R2157",
    "Parked at factory",
    "18/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "None",
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ],
  [
    "N/A - Idle",
    "OR15P0489",
    "Parked at factory",
    "18/09/2026",
    "N/A - Parked at factory",
    "Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "None",
    "Parked at factory",
    "24h (Parked at factory)",
    "None - Idle at Base",
    "None (Idle)",
    "N/A - Parked at factory",
    "Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "N/A - Parked at factory",
    "Parked at factory",
    0.0,
    "Pending Dispatch Order",
    0
  ]
];

  // Write Lifecycle Headers
  const hRange2 = lifecycleSheet.getRange(1, 1, 1, headersLifecycle.length);
  hRange2.setValues([headersLifecycle]);
  hRange2.setFontWeight('bold');
  hRange2.setBackground('#0E3A5D');
  hRange2.setFontColor('#FFFFFF');
  hRange2.setHorizontalAlignment('center');

  // Write Lifecycle Data
  lifecycleSheet.getRange(2, 1, dataLifecycle.length, headersLifecycle.length).setValues(dataLifecycle);

  // Lifecycle Formatting
  lifecycleSheet.getRange(2, 1, dataLifecycle.length, 1).setHorizontalAlignment('center').setFontWeight('bold'); // Trip ID
  lifecycleSheet.getRange(2, 2, dataLifecycle.length, 1).setHorizontalAlignment('center').setFontWeight('bold'); // Tanker
  lifecycleSheet.getRange(2, 4, dataLifecycle.length, 2).setHorizontalAlignment('center'); // Date & Time
  lifecycleSheet.getRange(2, 10, dataLifecycle.length, 1).setNumberFormat('#,##0.00').setHorizontalAlignment('right'); // Distance
  lifecycleSheet.getRange(2, 23, dataLifecycle.length, 1).setNumberFormat('#,##0.00').setHorizontalAlignment('right'); // Return Distance
  lifecycleSheet.getRange(2, 25, dataLifecycle.length, 1).setNumberFormat('₹#,##0').setHorizontalAlignment('right').setFontWeight('bold'); // Allowance

  for (let r = 2; r <= dataLifecycle.length + 1; r++) {
    lifecycleSheet.getRange(r, 1, 1, headersLifecycle.length).setBackground(r % 2 === 0 ? '#F8F9FA' : '#FFFFFF');
  }
  lifecycleSheet.setFrozenRows(1);
  for (let c = 1; c <= headersLifecycle.length; c++) {
    lifecycleSheet.autoResizeColumn(c);
  }

  Logger.log('✅ Successfully updated both Sheet1 and Trip_Lifecycle tabs with 100% verified WheelsEye telemetry!');
}
